### ISSUE TITLE
Sunmi.image() does not work.

### ISSUE THREAD

**Issue by bomwarut** [bistroo/capacitor-plugin-sunmi#4]
when i use Sunmi.image() it does not work.Do it use for print image in paper? i did not seem anything.I replace image option witn image url or base 64 image file it do not print.What this command use for?

**Comment by yooouuri** [comment]
It is used to print an image on the paper.

```typescript
import { Sunmi } from '@bistroo/capacitor-plugin-sunmi'

Sunmi.image({ image: 'some base64 image' })
```

**Comment by mbo2olivier** [comment]
Same issue, cannot print image with plugin

**Comment by mbo2olivier** [comment]
@bomwarut i have solve the issue.

I think the base64 image representation sentto the plugin is not correct: if like me you use a third party library (QRCode for example) for generating qrCode base64 representation, check the result string and remove the "data:image/png;base64," at beginning before sending to Sunmi.image method.
It's worked for me
